# Generated by Django 4.1.4 on 2022-12-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.ImageField(default="media/default.jpg", upload_to="media"),
        ),
    ]
